#!/bin/sh
set -euf

if [ -n "${DISPLAY-}" ]; then
  export FIFO_UEBERZUG="${TMPDIR:-/tmp}/lf-ueberzug-$$"

  cleanup() {
    exec 3>&-
    rm -- "$FIFO_UEBERZUG"
  }

  mkfifo -- "$FIFO_UEBERZUG"
  ueberzug layer -s <"$FIFO_UEBERZUG" &
  pid="$!"
  exec 3>"$FIFO_UEBERZUG"
  trap cleanup EXIT

  while waitpid "$pid"; do
    ueberzug layer -s <"$FIFO_UEBERZUG" &
    pid="$!"
  done &

  if ! [ -d "$HOME/.cache/lf" ]; then
    mkdir -p -- "$HOME/.cache/lf"
  fi

  lf "$@" 3>&-
else
  exec lf "$@"
fi
